name: saucelabs-cypress-automation

on:
  push:
    branches: [ ci ]
    
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm install

      - name: Cypress run
        run: npm run cypress:run

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report