name: saucelabs-cypress-automation

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Delete gh-pages branch
        uses: peaceiris/actions-delete-branch@v4
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}      
      
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm install

      - name: Cypress run
        run: npm run cypress:run

      - name: Merge report
        run: npm run combine:report

      - name: Generate report
        run: npm run generate:report

      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
